In [1]:
import pandas as pd 
import numpy as np

In [2]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
z = np.array([7, 8, 9])

In [4]:
np.concatenate((x,y))

array([1, 2, 3, 4, 5, 6])

In [4]:
a = np.array([[5,6],[7,8]])
b = np.array([[9,4]])
a

array([[5, 6],
       [7, 8]])

In [21]:
np.concatenate((x,y,z),axis=0)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.concatenate((a,b),axis=0)

array([[5, 6],
       [7, 8],
       [9, 4]])

In [6]:
concat =np.concatenate((a,b.T),axis=1)
concat

array([[5, 6, 9],
       [7, 8, 4]])

In [14]:
concat.reshape(3,-1)

array([[5, 6],
       [9, 7],
       [8, 4]])

In [15]:
np.vstack((a,b))

array([[5, 6],
       [7, 8],
       [9, 4]])

In [18]:
np.vstack((y,z))

array([[4, 5, 6],
       [7, 8, 9]])

In [19]:
np.hstack((y,z))

array([4, 5, 6, 7, 8, 9])

In [8]:
 np.random.randint(0,10)

2

In [39]:
a = np.random.randint(0,10,size = (2,3))
b = np.random.randint(0,[1,2,6])


In [40]:
a,b

(array([[8, 5, 8],
        [5, 8, 3]]),
 array([0, 1, 5]))

In [58]:
c = np.random.randint([1,2,6], 20)

In [59]:
np.concatenate((c,b))

array([19, 19, 12,  0,  1,  5])

In [60]:
np.vstack((a,b))

array([[8, 5, 8],
       [5, 8, 3],
       [0, 1, 5]])

In [61]:
np.hstack((c,b))

array([19, 19, 12,  0,  1,  5])

In [62]:
a = np.random.randint(10, size=(2, 3))
b = np.random.randint(10, size=(2, 3))

In [64]:
np.concatenate((a,b))

array([[2, 6, 5],
       [2, 5, 0],
       [8, 7, 9],
       [7, 0, 5]])

In [65]:
np.concatenate([a,b])

array([[2, 6, 5],
       [2, 5, 0],
       [8, 7, 9],
       [7, 0, 5]])

In [66]:
x = np.array([[1, 2, 3], [4, 5, 6]])
y = np.array([[7, 8, 9], [10, 11, 12], [13, 14, 15]])

print(x.shape)
print(y.shape)

x, y

(2, 3)
(3, 3)


(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]]))

In [67]:
np.concatenate((x,y))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [3]:
x = np.array([1, 2, 3, 99, 99, 3, 2, 1])
x

array([ 1,  2,  3, 99, 99,  3,  2,  1])

In [5]:
np.split(x,4)

[array([1, 2]), array([ 3, 99]), array([99,  3]), array([2, 1])]

In [6]:
np.split(x,[2,1])

[array([1, 2]), array([], dtype=int32), array([ 2,  3, 99, 99,  3,  2,  1])]

In [7]:
np.split(x,[2,5])

[array([1, 2]), array([ 3, 99, 99]), array([3, 2, 1])]

In [8]:
np.split(x,2)

[array([ 1,  2,  3, 99]), array([99,  3,  2,  1])]

In [9]:
np.split(x,[4])

[array([ 1,  2,  3, 99]), array([99,  3,  2,  1])]

In [12]:
np.split(x,[4])

[array([ 1,  2,  3, 99]), array([99,  3,  2,  1])]

In [20]:
k = np.arange(20).reshape(5,4)
# k = np.array(range(20)).reshape(5,4)
k

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [23]:
np.split(k,[1,3])

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [ ]:
np.split(ary, indices_or_sections, axis=0)

In [24]:
np.split(k,[1,3],axis=1)

[array([[ 0],
        [ 4],
        [ 8],
        [12],
        [16]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14],
        [17, 18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

In [26]:
np.vsplit(k,[1,3])

[array([[0, 1, 2, 3]]),
 array([[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]])]

In [30]:
upper,lower = np.split(k,[3])
upper,lower

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19]]))

In [32]:
left,right= np.hsplit(k,[3])
left,right

(array([[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10],
        [12, 13, 14],
        [16, 17, 18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]]))

In [33]:
np.hsplit(k,[3])

[array([[ 0,  1,  2],
        [ 4,  5,  6],
        [ 8,  9, 10],
        [12, 13, 14],
        [16, 17, 18]]),
 array([[ 3],
        [ 7],
        [11],
        [15],
        [19]])]

In [11]:
v = np.array([2, 1, 4, 3, 5])
v

array([2, 1, 4, 3, 5])

In [ ]:
np.sort(a, axis=-1, kind=None, order=None)

In [35]:
np.sort(v, axis=-1)

array([1, 2, 3, 4, 5])

In [15]:
h = np.array([[2,3], [5,2]])
h

array([[2, 3],
       [5, 2]])

In [16]:
np.sort(h, axis=0)

array([[2, 2],
       [5, 3]])

In [13]:
np.sort(h)

array([[2, 3],
       [2, 5]])

In [41]:
np.sort(v, axis=-1

TypeError: _sort_dispatcher() got an unexpected keyword argument 'inplace'

In [36]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [37]:
v

array([2, 1, 4, 3, 5])

In [39]:
v.sort()    ## inplace changed
v 

array([1, 2, 3, 4, 5])

In [40]:
v

array([1, 2, 3, 4, 5])

In [ ]:
randint(low, high=None, size=None, dtype=int)

In [9]:
twoD = np.random.randint(5, 100, (3, 3))
twoD

array([[23, 78, 42],
       [ 9, 67, 66],
       [78, 12, 10]])

In [10]:
np.sort(twoD)

array([[23, 42, 78],
       [ 9, 66, 67],
       [10, 12, 78]])

In [14]:
np.sort(twoD,axis=0)

array([[ 9, 12, 10],
       [23, 67, 42],
       [78, 78, 66]])

## <p style="background-color:#9d4f8c; font-family:newtimeroman; color:#FFF9ED; font-size:175%; text-align:center; border-radius:10px 10px;">Numpy Indexing & Selection</p>

<a id="1"></a>
<a href="#toc" class="btn btn-primary btn-sm" role="button" aria-pressed="true" 
style="color:blue; background-color:#dfa8e4" data-toggle="popover">Content</a>

In [30]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
arr[8]

8

In [32]:
arr[0:3]

array([0, 1, 2])

In [34]:
arr[0::2]

array([ 0,  2,  4,  6,  8, 10])

In [33]:
arr[::2]

array([ 0,  2,  4,  6,  8, 10])

In [35]:
arr = np.arange(0,50).reshape(10,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [36]:
arr[1:3,2:5]

array([[ 7,  8,  9],
       [12, 13, 14]])

In [37]:
arr[0:2][0:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [51]:
arr[0:2][0:1]

array([[0, 1, 2, 3, 4]])

In [45]:
arr[[0,2]]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [50]:
arr[[0,2],[0,2]]

array([ 0, 12])

In [58]:
arr[:, [2,4]]

array([[ 2,  4],
       [ 7,  9],
       [12, 14],
       [17, 19],
       [22, 24],
       [27, 29],
       [32, 34],
       [37, 39],
       [42, 44],
       [47, 49]])

In [54]:
jj = np.arange(1, 17).reshape(4, 4)

In [55]:
jj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [56]:
jj[1, [1, 3]]

array([6, 8])

In [59]:
jj[jj<8]

array([1, 2, 3, 4, 5, 6, 7])