In [2]:
import numpy as np

In [5]:
my_list = [5,10,15,20,25]

In [6]:
np.array(my_list)

array([ 5, 10, 15, 20, 25])

In [7]:
np.arange(5,26,5)

array([ 5, 10, 15, 20, 25])

In [8]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.empty((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.ones((4,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [13]:
np.full((4,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [15]:
np.array(range(2,17,2))

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [21]:
np.array(range(0,25)).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [22]:
np.linspace(start = [0,5,10,15,20], stop= [4, 9,14,19,24], num = 5, dtype = int, axis = 1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [30]:
np.random.rand(25).reshape(5,5)

array([[0.3011468 , 0.89835037, 0.52899779, 0.83535008, 0.84126445],
       [0.78048041, 0.10947808, 0.85883259, 0.49896627, 0.08632452],
       [0.10094109, 0.39265967, 0.62171535, 0.16896445, 0.27270327],
       [0.640535  , 0.70198453, 0.26555257, 0.51774506, 0.67888057],
       [0.55283117, 0.01777479, 0.61552199, 0.41870906, 0.53200866]])

In [37]:
np.random.randint(20,50, size = (3,4))

array([[24, 27, 27, 49],
       [37, 29, 27, 33],
       [42, 47, 21, 43]])

In [39]:
ranarr = np.random.randint(1,50,48)
ranarr

array([28, 15, 15, 40, 49, 11, 16,  8, 29, 22, 22, 23, 40, 13, 24,  5, 30,
        5, 23,  1, 25, 23, 42, 31, 32, 17,  1, 35, 42, 15, 26, 10,  2, 43,
       41, 34, 30, 37, 13, 36, 24, 17, 24, 31,  9, 23, 26,  3])

In [40]:
ranarr.reshape(6,8)

array([[28, 15, 15, 40, 49, 11, 16,  8],
       [29, 22, 22, 23, 40, 13, 24,  5],
       [30,  5, 23,  1, 25, 23, 42, 31],
       [32, 17,  1, 35, 42, 15, 26, 10],
       [ 2, 43, 41, 34, 30, 37, 13, 36],
       [24, 17, 24, 31,  9, 23, 26,  3]])

In [41]:
ranarr.reshape(6,-1)  ## 6 ya uygun ayarlama yapar(-1 çarpmayı tamamlar)

array([[28, 15, 15, 40, 49, 11, 16,  8],
       [29, 22, 22, 23, 40, 13, 24,  5],
       [30,  5, 23,  1, 25, 23, 42, 31],
       [32, 17,  1, 35, 42, 15, 26, 10],
       [ 2, 43, 41, 34, 30, 37, 13, 36],
       [24, 17, 24, 31,  9, 23, 26,  3]])

In [42]:
ranarr.reshape(8,-1)

array([[28, 15, 15, 40, 49, 11],
       [16,  8, 29, 22, 22, 23],
       [40, 13, 24,  5, 30,  5],
       [23,  1, 25, 23, 42, 31],
       [32, 17,  1, 35, 42, 15],
       [26, 10,  2, 43, 41, 34],
       [30, 37, 13, 36, 24, 17],
       [24, 31,  9, 23, 26,  3]])

In [44]:
mat  =np.arange(1,17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [47]:
mat[1:3,1:3]

array([[ 6,  7],
       [10, 11]])

In [48]:
mat[[1, 2], 1:3]

array([[ 6,  7],
       [10, 11]])

In [53]:
mat[1,::2]

array([5, 7])

In [54]:
mat[1][::2]

array([5, 7])

In [57]:
mat[1::2, ::2]

array([[ 5,  7],
       [13, 15]])

In [59]:
mat[mat<10]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
mat[mat>12]

array([13, 14, 15, 16])

In [63]:
mat[mat<10] + mat[mat>12]

ValueError: operands could not be broadcast together with shapes (9,) (4,) 

In [ ]:
df.TotalPayBenefits[2:3]

In [ ]:
df[“JobTitle”].value_counts().tail(3)

In [ ]:
liste=[]
for i in df[df["Year"]==2012]["TotalPayBenefits"]:
    if i > df["TotalPayBenefits"].mean():
        liste.append(i)
len(liste)

In [ ]:
sal_new = df.iloc[:, 1:4]
sal_new